apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: install-run
spec:
  taskRef:
    name: provision-cluster
  params:
    - name: PLATFORM
      value: aws
    - name: BASE_DOMAIN
      value: devcluster.openshift.com
    - name: CLUSTER_NAME
      value: pthangad-4
    - name: REGION
      value: us-east-2
    - name: REPLICAS
      value: "3"
    - name: OPENSHIFT_INSTALLER_IMAGE
      value: docker.io/praveen4g0/release-tests-bootstrap-image:v0.0.1
  workspaces:
    - name: install-dir
      persistentvolumeclaim:
        claimName: install-dir
    - name: secrets
      secret:
        secretName: aws-credentials
