apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: openshift-uninstall-run
spec:
  taskRef:
    name: destroy-cluster
  params:
    - name: OPENSHIFT_INSTALLER_IMAGE
      value: docker.io/praveen4g0/release-tests-bootstrap-image:v0.0.1
  workspaces:
    - name: install-dir
      persistentvolumeclaim:
        claimName: install-dir
