apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: openshift-pipelines-e2e-tests
spec:
  pipelineRef:
    name: release-tests
  timeout: 2h
  params:
  - name: OPENSHIFT_INSTALLER_IMAGE
    value: docker.io/praveen4g0/release-tests-bootstrap-image:v0.0.2
  - name: CLUSTER_NAME
    value: qe-ci
  - name: BASE_DOMAIN
    value: tekton.codereadyqe.com
  - name: OPERATOR-ENV
    value: prod
  - name: RELEASE-TESTS-IMAGE
    value: docker.io/praveen4g0/release-tests:v0.0.7
  - name: UPLOADER-HOST
    value: http://uploader-uploader.apps.cicd.tekton.codereadyqe.com
  workspaces:
  - name: install-dir
    persistentvolumeclaim:
      claimName: install-dir
  - name: aws-secrets
    secret:
      secretName: aws-credentials
  - name: psi-secrets
    secret:
      secretName: psi-cloud-creds
  - name: configmap
    configMap:
       name: subscription-store
       items:
       - key: subscription
         path: subscription.yaml