apiVersion: v1
kind: ConfigMap
metadata:
  name: subscription-store
data:
  subscription: |
    apiVersion: operators.coreos.com/v1alpha1
    kind: Subscription
    metadata:
      generation: 1
      name: openshift-pipelines-operator-rh
      namespace: openshift-operators
    spec:
      channel: ocp-4.4
      installPlanApproval: Automatic
      name: openshift-pipelines-operator-rh
      source: redhat-operators
      sourceNamespace: openshift-marketplace
      startingCSV: openshift-pipelines-operator.v1.0.1