apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: tutorial-tests
spec:
  workspaces:
    - name: install-dir
      mountPath: "/tekton/home/"
  params:
  - name: IMAGE
    type: string
    description: oc & tkn latest image
  - name: CLUSTER_NAME
    type: string
    description: Cluster name
    default: "openshift-pipelines-install"
  - name: UPLOADER-HOST
    type: string
    description: If you have this installed then set it here.
  steps:
    - name: run-tutorial-tests
      image: $(params.IMAGE)
      workingDir: /tutorial/pipelines-tutorial
      env:
        - name: UPLOADER_USERNAME
          valueFrom:
            secretKeyRef:
              name: openshift-install
              key: uploader-username
        - name: UPLOADER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: openshift-install
              key: uploader-password
      securityContext:
        runAsUser: 0
        privileged: true
      script: |
        #!/usr/bin/env bash
        set -e -u -o pipefail

        clean() {  echo -n " Running Cleanup... "; oc delete project pipelines-tutorial; curr_ts=`date +"%Y-%m-%d-%H-%M-%S"`; upload logs CI/$(params.CLUSTER_NAME)/tutorial-report/${curr_ts}/result.log; }
        trap clean EXIT

        # exporting required
        export KUBECONFIG=$(workspaces.install-dir.path)/cluster/$(params.CLUSTER_NAME)/auth/kubeconfig


        echo -n "Running pipelines tutorial..."
        # Run Tutorial pipelines Tests
        ./demo.sh setup | tee -a logs || true
        ./demo.sh run | tee -a logs || true
        echo -n "Done."

        [[ -n $(params.UPLOADER-HOST) && \
        -n ${UPLOADER_USERNAME} && \
        -n ${UPLOADER_PASSWORD} ]] || exit 0

        function upload() {
          dest="$2"
          [[ -z ${dest} ]] && dest="CI/$(params.CLUSTER_NAME)/$(basename ${1})"
          curl -f -u ${UPLOADER_USERNAME}:${UPLOADER_PASSWORD} \
            -F path=${dest} \
            -F file=@${1} \
            $(params.UPLOADER-HOST)/upload
        }
      volumeMounts:
      - name: source
        mountPath: /tutorial
  volumes:
  - name: source
    gitRepo:
      repository: https://github.com/praveen4g0/pipelines-tutorial.git
      revision: tutorial-tests